### ISSUE TITLE
0-arity function in spec should still be parenthesized

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#41]
After removing parens for 0-arity types, this happens:

```elixir
@spec foo() :: :ok
```

is formatted as

```elixir
@spec foo :: :ok
```

but it should remain parenthesized given `foo` is a function and not a type.

**Comment by uohzxela** [comment]
My plan is to strip parens for all 0-arity terms on the right side of :: operator, since I assume they are all types (correct me if I'm wrong).

For the left side, how do we know whether `foo` is a function or a type?

```
@spec foo :: {number, String.t}
@type foo :: {number, String.t}
```

I think we can keep track whether we are in `@spec` or `@type` call before formatting the left side of `::` operator. If it's `@spec`, then we add parens to the 0-arity term. Otherwise, we strip parens from it. Thoughts?

**Comment by whatyouhide** [comment]
spec, calback, macrocallback are functions. type, typep, opaque are types.

**Comment by whatyouhide** [comment]
Use this notion to properly add parens is what I meant :)
