### ISSUE TITLE
Maintain keyword syntactic sugar for non-keywords

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#44]
```elixir
[:foo, bar: :baz]
```

should be formatted without changes but it gets formatted to 

```elixir
[:foo, {:bar, :baz}]
```

**Comment by uohzxela** [comment]
The AST is `[:foo, {:bar, :baz}]` so there is no way to know if the user has used keyword synactic sugar or not.

If we were to go about implementing this, should we enforce keyword syntactic sugar for all tuples of size 2 in non-keyword list? Personally, I prefer desugaring since there is a clearer delineation between elements with the tuple curly brackets.

**Comment by whatyouhide** [comment]
Yeah I know there is no way to know, I meant to always go with the sugar syntax. I always use that anyways. Thoughts @josevalim @lexmag?

**Comment by josevalim** [comment]
We should go with the keywords list one. Question: is each atom in the
keywords list wrapped in a __block__?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by uohzxela** [comment]
Okay, we can go with the sugar syntax.

@josevalim only the value atom is wrapped in a block:

```
iex(28)> Code.string_to_quoted "[:foo, bar: :baz]", wrap_literals_in_blocks: true
{:ok,
 {:__block__, [line: 1],
  [[{:__block__, [line: 1], [:foo]}, {:bar, {:__block__, [line: 1], [:baz]}}]]}}
```
