### ISSUE TITLE
Don't split tuples the same way as maps, lists, and friends

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#50]
Right now tuples are formatted multiline when they don't fit:

```elixir
{
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
  bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
  ccccccccccccccccccccccccccccccccccccc,
}
```

Personally I never use this convention nor have I seen it in any code that I can recall. However, I am not sure how to proceed here. Thoughts @josevalim @lexmag?

**Comment by josevalim** [comment]
For now multi-line only for key-value data structures.

**Comment by whatyouhide** [comment]
@uohzxela this should be a easy one to tackle. :)

**Comment by uohzxela** [comment]
@whatyouhide I think we are still using multiline tuples in some cases if i'm not wrong, like the example you gave recently in a PR: https://github.com/uohzxela/ex_format/pull/67#discussion_r132835054 and also issue: https://github.com/uohzxela/ex_format/issues/48 :P

**Comment by whatyouhide** [comment]
@uohzxela those are not considered tuples but tuple calls. I'm talking about tuple literals.

**Comment by uohzxela** [comment]
@whatyouhide since we already implemented multi-line tuple literals, why not we keep them as we are using them as an abstraction for multi-line tuple calls? Also, if some user unwittingly has a very very long tuple, it can get split into multiple lines however unusual it may be. But if you really want to eliminate multi-line tuple literals, I can rewrite the code accordingly. :)

**Comment by whatyouhide** [comment]
We just never write multiline tuples in real-world Elixir code, so yes let's rewrite to make tuples not go multi-line (except for tuple calls). 👍

**Comment by uohzxela** [comment]
No problem @whatyouhide, will work on it after I finished the documentation.

**Comment by uohzxela** [comment]
Reopened because of this example I found in Elixir source:

```
:ets.insert(table, {
  doc_tuple,
  line,
  kind,
  merge_signatures(current_sign, signature, 1),
  if(is_nil(doc), do: current_doc, else: doc)
})
```

Right now this is formatted as a very long single-line tuple. In light of this example, should we bring back splitting for tuples? @whatyouhide

**Comment by josevalim** [comment]
IMO, we should format it as:

```elixir
:ets.insert(table, {doc_tuple, line, kind,
                    merge_signatures(current_sign, signature, 1),
                    if(is_nil(doc), do: current_doc, else: doc)})
```

if someone doesn't like it much, then you can just put the other expressions in variables and then it should concisely fit a single line. The rationale for this choice is because the one per line looks really verbose when they are all variables: 

```elixir
:ets.insert(table, {
  doc_tuple,
  line,
  kind,
  signature,
  doc
})
```

And using only variables is arguably the most readable code, so I would rather make the most readable code look tidy than trying to make non-readable code pretty.

@lpil, am I also correct to say that, if we were using inspect algebra, our options would be between:

```elixir
:ets.insert(table,
            {doc_tuple, line, kind,
             merge_signatures(current_sign, signature, 1),
             if(is_nil(doc), do: current_doc, else: doc)})
```

and

```elixir
:ets.insert(table,
            {
              doc_tuple,
              line,
              kind,
              merge_signatures(current_sign, signature, 1),
              if(is_nil(doc), do: current_doc, else: doc)
            })
```

?

**Comment by lexmag** [comment]
I like
```elixir
:ets.insert(table,
            {doc_tuple, line, kind,
             merge_signatures(current_sign, signature, 1),
             if(is_nil(doc), do: current_doc, else: doc)})
```
the most.
More than `:ets.insert(table, {doc_tuple, line, kind,` variant (my second favourite) because it makes less empty space on the left side, and subjectively makes mental parsing of that huge second argument easier. :bowtie:

**Comment by lpil** [comment]
I believe that any of the above could be implemented with algebra, just varying levels of fiddy-ness :)

**Comment by uohzxela** [comment]
Sounds like using Inspect.Algebra is the way to go for very long tuples, thanks all for the discussion!
