### ISSUE TITLE
Don't parenthesize some special calls

### ISSUE THREAD

**Issue by whatyouhide** [uohzxela/ex_format#51]
Some calls are "special": `plug` from `Plug`, `assert` from ExUnit, `field` from Ecto and so on. How can we not parenthesize them? `assert` can for now be made part of the special non-parenthesizeable calls but there should be a more generic way I guess.

\cc @josevalim and @lexmag here as well :)

**Comment by uohzxela** [comment]
Hardcoded `assert` as part of this commit: https://github.com/uohzxela/ex_format/commit/c12502e11bdf219eedb98572e2550f9a6a2be8cc

For the rest, would it be a good idea to test more on Phoenix/Plug/Ecto code so that we know which are the more commonly used parenless calls? If there are not too many of them, we can hardcode them for now. Otherwise, we need a more generic solution like @whatyouhide mentioned. Thoughts?

**Comment by whatyouhide** [comment]
We probably need a more generic solution because the number of DSLs that are commonly used without parens is not under our control.

**Comment by uohzxela** [comment]
@whatyouhide Just throwing out some ideas. How about we write a script to parse all the files in Phoenix/Ecto source, and collect the function names which are defined as defmacro and friends? We put the names in a file and initialize the ExFormat's state with it? This is assuming that the parenless function calls are usually defined as macros.

**Comment by whatyouhide** [comment]
We can't not parenthesize all macros in libraries, for example gettext macros use no spaces. We should let libraries express which macros they want not parenthesized somehow.

**Comment by lpil** [comment]
How would you know if the library macro is being called or if it's another function with the same name? Sounds like you would need to actually be compiling the code to tell.

**Comment by whatyouhide** [comment]
yes its a nontrivial problem that requires some thinking and experimentation i think :)

**Comment by uohzxela** [comment]
Another day another idea: Modify Elixir source to find out whether the programmer has included parentheses for `foo(x, y)` at the tokenizer level, and propagate that information up to the AST.

The downside is we might lose some consistency if the programmer is not disciplined enough to enforce parens for non-macro calls, but I feel that's a minor compromise since we are still enforcing parens for `Module.foo`, calls in pipelines and friends. Also, I assume most Elixir peeps are writing Phoenix code so I guess there is a significant amount of parenless calls like `render`, `json` and `redirect` in the wild.

A variant of this solution may also be used to solve the problem that @whatyouhide raised in issue https://github.com/uohzxela/ex_format/issues/28#issuecomment-319493664.

What do y'all think?

**Comment by lpil** [comment]
I like the idea of a hybrid approach where you enforce a style when you know for sure and preserve programmer choice when you cannot

**Comment by uohzxela** [comment]
@whatyouhide thanks for cleaning up the stale issues :)
