### ISSUE TITLE
Eliminate agent state for lines and inline comments

### ISSUE THREAD

**Issue by uohzxela** [uohzxela/ex_format#69]

**Comment by lpil** [comment]
Alternatively you could keep the agents but refer to them with their pid instead of naming them. This way you'd get the flexible mutable state in your formatter but you no longer have global state so you can format multiple files concurrently.

Could be a good first step. :)

**Comment by uohzxela** [comment]
@lpil thanks for the suggestion, learnt something new today :)

**Comment by whatyouhide** [comment]
While it is true, there's almost no distinction between keeping pid in the state and just keeping the lines/comments in the state except that you don't have to put the "updated pid" (which doesnt update of course) back in the state, but that's a minor thing to do so I would definitely drop agents and go with just data in the state. After all agents don't really make sense for this use case since everything we do is functional and we never need to access the state from different processes.

**Comment by lpil** [comment]
Agree, generally it's better to keep everything simply functional I think.
More just pointing out an alternative way to use processes that doesn't
have as many disadvantages as this method :)
