### ISSUE TITLE
Do not add new line after ->

### ISSUE THREAD

**Issue by chulkilee** [uohzxela/ex_format#88]
Hi, I tested ex_format and found it breaks line between `->` and following clauses. I don't see any style guide on this case, so can we leave it? Or at least leave it for single line clause.

```elixir
# desired
case foo() do
  :ok -> "foo"
  _ -> "bar"
end
```

```elixir
# ex_format output
case foo() do
  :ok ->
    "foo"
  _ ->
    "bar"
end
```

**Comment by uohzxela** [comment]
Hi @chulkilee! Thanks for testing ExFormat :)

Initially, I thought the same too - leaving it for single line clause. However, I think it's better to do a line break after `->` for overall consistency since all the clauses can start on the nested new line.

@whatyouhide @josevalim what do you think? This is something we never really discussed as well.

**Comment by KronicDeth** [comment]
In IntelliJ Elixir, I set it up so that if all the clauses work as one-liners, then one-liners is allowed, but if any clause is multi-line, then they all have to be multi-line, so in a given set of clauses the new line after `->` remains consistent.

**Comment by uohzxela** [comment]
Oh hey @KronicDeth, thanks for your input. Great work on IntelliJ Elixir btw! Just curious, what do you use to format Elixir source code in IntelliJ?

**Comment by KronicDeth** [comment]
JetBrains, as part of OpenAPI supplies code for defining formatters.  I used this in [IntelliJ Elixir](https://github.com/KronicDeth/intellij-elixir/pull/724).  The part of the formatting libraries I'm using only manipulates whitespace.

There are 3 extensions I had to define https://github.com/KronicDeth/intellij-elixir/blob/70ecf4e538a30f7f851c8888cd43428be544b46a/resources/META-INF/plugin.xml#L88-L91
1. `codeStyleSettingsProvider`
2. `lang.formatter`
3. `langCodeStyleSettingsProvider`

1 and 3 are for tracking the configuration, so the part you'd be interested in is the `lang.formatter`, [`org.elixir_lang.formatting.ModelBuilder`](https://github.com/KronicDeth/intellij-elixir/blob/70ecf4e538a30f7f851c8888cd43428be544b46a/src/org/elixir_lang/formatting/ModelBuilder.java).  Rules about spacing are supplied by the `SpacingBuilder` from [`ModelBuilder.createSpacingBuilder`](https://github.com/KronicDeth/intellij-elixir/blob/70ecf4e538a30f7f851c8888cd43428be544b46a/src/org/elixir_lang/formatting/ModelBuilder.java#L41-L113).  It has rules for before, after, around, and inside different lexer nodes (which uses the `ASTNode` class in Java).  

[`ModelBuilder.createModel`](https://github.com/KronicDeth/intellij-elixir/blob/70ecf4e538a30f7f851c8888cd43428be544b46a/src/org/elixir_lang/formatting/ModelBuilder.java#L140-L158) creates a [`org.elixir_lang.formatter.Block`](https://github.com/KronicDeth/intellij-elixir/blob/70ecf4e538a30f7f851c8888cd43428be544b46a/src/org/elixir_lang/formatter/Block.java), which is a subclass of `com.intellij.psi.formatter.common.AbstractBlock`.  The blocks in OpenAPI can are in charge of 3 formatting controls:
1. WrapType (what to do when you go past the column limit
2. Indent (how to indent relative to an anchor, either the last line OR the last direct parent)
3. Alignment (how to align Blocks that share the same Alignment, so you can do stuff like
```
along_variable_name_pushes_everything_over = 1
b                                          = 2
```

They also generate the Blocks for their children, so you can have different rules for nested stuff than if they were top-level.

So, the way I did the "one-liner if all can be one-liners" is using the ` Wrap.createWrap(WrapType.CHOP_DOWN_IF_LONG, true)` because when `CHOP_DOWN_IF_LONG` is used and all elements share the same `Wrap` instance they all wrap at the same time.  This is also how I make keyword list all wrap at the same time if any one keyword pair is past the column limit.

How OpenAPI uses these `WrapType`s to actually formatter the code is unfortunately in some pretty gnarly code (that was already written thankfully because it was) written kinda like an event callback system to allow the user to interrupt the formatting when it takes too long like most of the stuff in IDEs.

The general impression from the code is there's a lot of look-ahead and back-propagation because the rules you can define can make parent nodes wrap or align to children if needed and the Wrap and WrapType share require looking ahead to see if anything sharing the instance wraps, but it is a limited look-ahead as having everything share the same `Wrap` deep down didn't work.

**Comment by uohzxela** [comment]
@KronicDeth That's super cool, never knew IntelliJ has that functionality. Thanks for sharing your knowledge! :)

**Comment by uohzxela** [comment]
@chulkilee the new formatter mentioned at https://github.com/uohzxela/ex_format/issues/90#issuecomment-326715312 can preserve the desired case:

```
case foo() do
  :ok -> "foo"
  _ -> "bar"
end
```
